//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timerom.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timerom.App.ResourceText", typeof(ResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the Category “{0}” and all its subcategories? You can’t undo this action..
        /// </summary>
        public static string DESCRIPTION_DELETE_CATEGORY {
            get {
                return ResourceManager.GetString("DESCRIPTION_DELETE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the Subcategory “{0}”? You can’t undo this action..
        /// </summary>
        public static string DESCRIPTION_DELETE_SUBCATEGORY {
            get {
                return ResourceManager.GetString("DESCRIPTION_DELETE_SUBCATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the task “{0}”? You can’t undo this action..
        /// </summary>
        public static string DESCRIPTION_DELETE_TASK {
            get {
                return ResourceManager.GetString("DESCRIPTION_DELETE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the goals of this App is to have a creative design. And for that, nothing better than using images to illustrate and amuse the user, right?
        ///
        ///All images used have a free license for use, and as a thank you, we leave below the links to the sites that our team used :).
        /// </summary>
        public static string DESCRIPTION_ILUSTRATIONS_INFORMATIONS {
            get {
                return ResourceManager.GetString("DESCRIPTION_ILUSTRATIONS_INFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can imagine that the sum of causes and results is always 100%, but that&apos;s not true, it&apos;s just a coincidence that 80% and 20% equal 100%. The results and causes can represent different values, that is, the sum does not necessarily have to result in 100%..
        /// </summary>
        public static string DESCRIPTION_OFTEN_MISINTERPRETED {
            get {
                return ResourceManager.GetString("DESCRIPTION_OFTEN_MISINTERPRETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the rule to focus on the 20% that are generating 80% of your results or even avoid the 20% generating 80% of your problems. It all depends on where you apply this rule..
        /// </summary>
        public static string DESCRIPTION_PARETO_PRINCIPLE_BENEFITS {
            get {
                return ResourceManager.GetString("DESCRIPTION_PARETO_PRINCIPLE_BENEFITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • 80% of a company’s revenue is generated by 20% of its customers..
        /// </summary>
        public static string DESCRIPTION_PARETO_PRINCIPLE_EXEMPLE_1 {
            get {
                return ResourceManager.GetString("DESCRIPTION_PARETO_PRINCIPLE_EXEMPLE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • 80% of problems in a work team are generated by only 20% of team members..
        /// </summary>
        public static string DESCRIPTION_PARETO_PRINCIPLE_EXEMPLE_2 {
            get {
                return ResourceManager.GetString("DESCRIPTION_PARETO_PRINCIPLE_EXEMPLE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • 20% of all websites you use are responsible for 80% of the time you spend on the internet..
        /// </summary>
        public static string DESCRIPTION_PARETO_PRINCIPLE_EXEMPLE_3 {
            get {
                return ResourceManager.GetString("DESCRIPTION_PARETO_PRINCIPLE_EXEMPLE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pareto Principle or 80-20 rule, is an aphorism which asserts that 80% of results (outputs) are generated by just 20% of cause (inputs) for any given event. This concept can be applied to both personal life and major events and businesses..
        /// </summary>
        public static string DESCRIPTION_PARETO_PRINCIPLE_WHAT_IS {
            get {
                return ResourceManager.GetString("DESCRIPTION_PARETO_PRINCIPLE_WHAT_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No need to accelerate, just don&apos;t stop..
        /// </summary>
        public static string PHRASE_MENU_FLYOUT_1 {
            get {
                return ResourceManager.GetString("PHRASE_MENU_FLYOUT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TITLE_ABOUT {
            get {
                return ResourceManager.GetString("TITLE_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this project.
        /// </summary>
        public static string TITLE_ABOUT_THIS_PROJECT {
            get {
                return ResourceManager.GetString("TITLE_ABOUT_THIS_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        public static string TITLE_ABSTRACT {
            get {
                return ResourceManager.GetString("TITLE_ABSTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulated percentage.
        /// </summary>
        public static string TITLE_ACCUMULATED_PERCENTAGE {
            get {
                return ResourceManager.GetString("TITLE_ACCUMULATED_PERCENTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string TITLE_ACTIVITIES {
            get {
                return ResourceManager.GetString("TITLE_ACTIVITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Analytic.
        /// </summary>
        public static string TITLE_ACTIVITY_ANALYTIC {
            get {
                return ResourceManager.GetString("TITLE_ACTIVITY_ANALYTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity progress.
        /// </summary>
        public static string TITLE_ACTIVITY_PROGRESS {
            get {
                return ResourceManager.GetString("TITLE_ACTIVITY_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Neutral Category.
        /// </summary>
        public static string TITLE_ADD_NEUTRAL_CATEGORY {
            get {
                return ResourceManager.GetString("TITLE_ADD_NEUTRAL_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Productive Category.
        /// </summary>
        public static string TITLE_ADD_PRODUCTIVE_CATEGORY {
            get {
                return ResourceManager.GetString("TITLE_ADD_PRODUCTIVE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string TITLE_ADD_TASK {
            get {
                return ResourceManager.GetString("TITLE_ADD_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Unproductive Category.
        /// </summary>
        public static string TITLE_ADD_UNPRODUCTIVE_CATEGORY {
            get {
                return ResourceManager.GetString("TITLE_ADD_UNPRODUCTIVE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytic.
        /// </summary>
        public static string TITLE_ANALYTIC {
            get {
                return ResourceManager.GetString("TITLE_ANALYTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It belongs to the category:.
        /// </summary>
        public static string TITLE_BELONGS_CATEGORY_TWO_POINTS {
            get {
                return ResourceManager.GetString("TITLE_BELONGS_CATEGORY_TWO_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string TITLE_BOOKS {
            get {
                return ResourceManager.GetString("TITLE_BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        public static string TITLE_BREAKFAST {
            get {
                return ResourceManager.GetString("TITLE_BREAKFAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string TITLE_CALL {
            get {
                return ResourceManager.GetString("TITLE_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TITLE_CANCEL {
            get {
                return ResourceManager.GetString("TITLE_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string TITLE_CATEGORIES {
            get {
                return ResourceManager.GetString("TITLE_CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name:.
        /// </summary>
        public static string TITLE_CATEGORY_NAME_TWO_POINTS {
            get {
                return ResourceManager.GetString("TITLE_CATEGORY_NAME_TWO_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an option.
        /// </summary>
        public static string TITLE_CHOOSE_AN_OPTION {
            get {
                return ResourceManager.GetString("TITLE_CHOOSE_AN_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your option.
        /// </summary>
        public static string TITLE_CHOOSE_YOUR_OPTION {
            get {
                return ResourceManager.GetString("TITLE_CHOOSE_YOUR_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to fill the task title.
        /// </summary>
        public static string TITLE_CLICK_HERE_FILL_TASK_TITLE {
            get {
                return ResourceManager.GetString("TITLE_CLICK_HERE_FILL_TASK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click in the bars to see more details..
        /// </summary>
        public static string TITLE_CLICK_IN_THE_BARS {
            get {
                return ResourceManager.GetString("TITLE_CLICK_IN_THE_BARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string TITLE_CONTACT_US {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string TITLE_CONTINUE {
            get {
                return ResourceManager.GetString("TITLE_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string TITLE_COURSES {
            get {
                return ResourceManager.GetString("TITLE_COURSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Category.
        /// </summary>
        public static string TITLE_CREATE_CATEGORY {
            get {
                return ResourceManager.GetString("TITLE_CREATE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Subcategory.
        /// </summary>
        public static string TITLE_CREATE_SUBCATEGORY {
            get {
                return ResourceManager.GetString("TITLE_CREATE_SUBCATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create task.
        /// </summary>
        public static string TITLE_CREATE_TASK {
            get {
                return ResourceManager.GetString("TITLE_CREATE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom dates.
        /// </summary>
        public static string TITLE_CUSTOM_DATES {
            get {
                return ResourceManager.GetString("TITLE_CUSTOM_DATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string TITLE_DASHBOARD {
            get {
                return ResourceManager.GetString("TITLE_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string TITLE_DAY {
            get {
                return ResourceManager.GetString("TITLE_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string TITLE_DAYS {
            get {
                return ResourceManager.GetString("TITLE_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        public static string TITLE_DELETE_CATEGORY {
            get {
                return ResourceManager.GetString("TITLE_DELETE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Subcategory.
        /// </summary>
        public static string TITLE_DELETE_SUBCATEGORY {
            get {
                return ResourceManager.GetString("TITLE_DELETE_SUBCATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Task.
        /// </summary>
        public static string TITLE_DELETE_TASK {
            get {
                return ResourceManager.GetString("TITLE_DELETE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string TITLE_DESCRIPTION_TWO_POINTS {
            get {
                return ResourceManager.GetString("TITLE_DESCRIPTION_TWO_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string TITLE_DETAILS {
            get {
                return ResourceManager.GetString("TITLE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        public static string TITLE_DINNER {
            get {
                return ResourceManager.GetString("TITLE_DINNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty list.
        /// </summary>
        public static string TITLE_EMPTY_LIST {
            get {
                return ResourceManager.GetString("TITLE_EMPTY_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends:.
        /// </summary>
        public static string TITLE_ENDS_TWO_POINTS {
            get {
                return ResourceManager.GetString("TITLE_ENDS_TWO_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string TITLE_FACEBOOK {
            get {
                return ResourceManager.GetString("TITLE_FACEBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string TITLE_FAMILY {
            get {
                return ResourceManager.GetString("TITLE_FAMILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string TITLE_FOOD {
            get {
                return ResourceManager.GetString("TITLE_FOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for the last 7 days.
        /// </summary>
        public static string TITLE_FOR_THE_LAST_SEVEN_DAYS {
            get {
                return ResourceManager.GetString("TITLE_FOR_THE_LAST_SEVEN_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From {0} to {1}.
        /// </summary>
        public static string TITLE_FROM_TO {
            get {
                return ResourceManager.GetString("TITLE_FROM_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gym.
        /// </summary>
        public static string TITLE_GYM {
            get {
                return ResourceManager.GetString("TITLE_GYM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TITLE_HOME {
            get {
                return ResourceManager.GetString("TITLE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string TITLE_HOUR {
            get {
                return ResourceManager.GetString("TITLE_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string TITLE_HOURS {
            get {
                return ResourceManager.GetString("TITLE_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons and Illustrations used.
        /// </summary>
        public static string TITLE_ICONS_ILLUSTRATIONS_USED {
            get {
                return ResourceManager.GetString("TITLE_ICONS_ILLUSTRATIONS_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve your time.
        /// </summary>
        public static string TITLE_IMPROVE_YOUR_TIME {
            get {
                return ResourceManager.GetString("TITLE_IMPROVE_YOUR_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string TITLE_INSTAGRAM {
            get {
                return ResourceManager.GetString("TITLE_INSTAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is part of the 80%.
        /// </summary>
        public static string TITLE_IT_IS_PART_80_PERCENT {
            get {
                return ResourceManager.GetString("TITLE_IT_IS_PART_80_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. What is?.
        /// </summary>
        public static string TITLE_ITEM_1_WHAT_IS {
            get {
                return ResourceManager.GetString("TITLE_ITEM_1_WHAT_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Examples.
        /// </summary>
        public static string TITLE_ITEM_2_EXAMPLES {
            get {
                return ResourceManager.GetString("TITLE_ITEM_2_EXAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Often misinterpreted.
        /// </summary>
        public static string TITLE_ITEM_3_OFTEN_MISINTERPRETED {
            get {
                return ResourceManager.GetString("TITLE_ITEM_3_OFTEN_MISINTERPRETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Benefits.
        /// </summary>
        public static string TITLE_ITEM_4_BENEFITS {
            get {
                return ResourceManager.GetString("TITLE_ITEM_4_BENEFITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last days.
        /// </summary>
        public static string TITLE_LAST_DAYS {
            get {
                return ResourceManager.GetString("TITLE_LAST_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        public static string TITLE_LAST_MONTH {
            get {
                return ResourceManager.GetString("TITLE_LAST_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        public static string TITLE_LUNCH {
            get {
                return ResourceManager.GetString("TITLE_LUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetings.
        /// </summary>
        public static string TITLE_MEETINGS {
            get {
                return ResourceManager.GetString("TITLE_MEETINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string TITLE_MINUTE {
            get {
                return ResourceManager.GetString("TITLE_MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string TITLE_MINUTES {
            get {
                return ResourceManager.GetString("TITLE_MINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string TITLE_NEUTRAL {
            get {
                return ResourceManager.GetString("TITLE_NEUTRAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No task for this date..
        /// </summary>
        public static string TITLE_NO_TASK_THIS_DATE {
            get {
                return ResourceManager.GetString("TITLE_NO_TASK_THIS_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pareto Principle.
        /// </summary>
        public static string TITLE_PARETO_PRINCIPLE {
            get {
                return ResourceManager.GetString("TITLE_PARETO_PRINCIPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of cause.
        /// </summary>
        public static string TITLE_PERCENTAGE_CAUSE {
            get {
                return ResourceManager.GetString("TITLE_PERCENTAGE_CAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of the result.
        /// </summary>
        public static string TITLE_PERCENTAGE_RESULT {
            get {
                return ResourceManager.GetString("TITLE_PERCENTAGE_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal projects.
        /// </summary>
        public static string TITLE_PERSONAL_PROJECTS {
            get {
                return ResourceManager.GetString("TITLE_PERSONAL_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner.
        /// </summary>
        public static string TITLE_PLANNER {
            get {
                return ResourceManager.GetString("TITLE_PLANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcasts.
        /// </summary>
        public static string TITLE_PODCASTS {
            get {
                return ResourceManager.GetString("TITLE_PODCASTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string TITLE_PRIVACY_POLICY {
            get {
                return ResourceManager.GetString("TITLE_PRIVACY_POLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product search.
        /// </summary>
        public static string TITLE_PRODUCT_SEARCH {
            get {
                return ResourceManager.GetString("TITLE_PRODUCT_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productive.
        /// </summary>
        public static string TITLE_PRODUCTIVE {
            get {
                return ResourceManager.GetString("TITLE_PRODUCTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        public static string TITLE_PURCHASES {
            get {
                return ResourceManager.GetString("TITLE_PURCHASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string TITLE_RANKING {
            get {
                return ResourceManager.GetString("TITLE_RANKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string TITLE_REPORTS {
            get {
                return ResourceManager.GetString("TITLE_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TITLE_SAVE {
            get {
                return ResourceManager.GetString("TITLE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salving ....
        /// </summary>
        public static string TITLE_SAVING {
            get {
                return ResourceManager.GetString("TITLE_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name.
        /// </summary>
        public static string TITLE_SEARCH_BY_NAME {
            get {
                return ResourceManager.GetString("TITLE_SEARCH_BY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Timer.
        /// </summary>
        public static string TITLE_SEE_TIMER {
            get {
                return ResourceManager.GetString("TITLE_SEE_TIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Category.
        /// </summary>
        public static string TITLE_SELECT_CATEGORY {
            get {
                return ResourceManager.GetString("TITLE_SELECT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category for your Task.
        /// </summary>
        public static string TITLE_SELECT_CATEGORY_FOR_YOUR_TASK {
            get {
                return ResourceManager.GetString("TITLE_SELECT_CATEGORY_FOR_YOUR_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Subcategory for your Task..
        /// </summary>
        public static string TITLE_SELECT_SUBCATEGORY_YOUR_TASK {
            get {
                return ResourceManager.GetString("TITLE_SELECT_SUBCATEGORY_YOUR_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social media.
        /// </summary>
        public static string TITLE_SOCIAL_MEDIA {
            get {
                return ResourceManager.GetString("TITLE_SOCIAL_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string TITLE_SPORT {
            get {
                return ResourceManager.GetString("TITLE_SPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Task.
        /// </summary>
        public static string TITLE_START_TASK {
            get {
                return ResourceManager.GetString("TITLE_START_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts:.
        /// </summary>
        public static string TITLE_STARTS_TWO_POINTS {
            get {
                return ResourceManager.GetString("TITLE_STARTS_TWO_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studies.
        /// </summary>
        public static string TITLE_STUDIES {
            get {
                return ResourceManager.GetString("TITLE_STUDIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studying English.
        /// </summary>
        public static string TITLE_STUDYING_ENGLISH {
            get {
                return ResourceManager.GetString("TITLE_STUDYING_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub categories:.
        /// </summary>
        public static string TITLE_SUBCATEGORIES_TITLE_TWO_POINTS {
            get {
                return ResourceManager.GetString("TITLE_SUBCATEGORIES_TITLE_TWO_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory:.
        /// </summary>
        public static string TITLE_SUBCATEGORY_TITLE_TWO_POINTS {
            get {
                return ResourceManager.GetString("TITLE_SUBCATEGORY_TITLE_TWO_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string TITLE_SUCCESS {
            get {
                return ResourceManager.GetString("TITLE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supermarket.
        /// </summary>
        public static string TITLE_SUPERMARKET {
            get {
                return ResourceManager.GetString("TITLE_SUPERMARKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task details.
        /// </summary>
        public static string TITLE_TASK_DETAILS {
            get {
                return ResourceManager.GetString("TITLE_TASK_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task title.
        /// </summary>
        public static string TITLE_TASK_TITLE {
            get {
                return ResourceManager.GetString("TITLE_TASK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TITLE_TASKS {
            get {
                return ResourceManager.GetString("TITLE_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        public static string TITLE_TECHNOLOGY {
            get {
                return ResourceManager.GetString("TITLE_TECHNOLOGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is {0}% of your day..
        /// </summary>
        public static string TITLE_THIS_IS_PERCENTAGE_YOUR_DAY {
            get {
                return ResourceManager.GetString("TITLE_THIS_IS_PERCENTAGE_YOUR_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is resulting in:.
        /// </summary>
        public static string TITLE_THIS_IS_RESULTING_IN {
            get {
                return ResourceManager.GetString("TITLE_THIS_IS_RESULTING_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        public static string TITLE_THIS_MONTH {
            get {
                return ResourceManager.GetString("TITLE_THIS_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TITLE_TOTAL {
            get {
                return ResourceManager.GetString("TITLE_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total of {0} tasks.
        /// </summary>
        public static string TITLE_TOTAL_OF_TASKS {
            get {
                return ResourceManager.GetString("TITLE_TOTAL_OF_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        public static string TITLE_TOUR {
            get {
                return ResourceManager.GetString("TITLE_TOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string TITLE_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("TITLE_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unproductive.
        /// </summary>
        public static string TITLE_UNPRODUCTIVE {
            get {
                return ResourceManager.GetString("TITLE_UNPRODUCTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Category.
        /// </summary>
        public static string TITLE_UPDATE_CATEGORY {
            get {
                return ResourceManager.GetString("TITLE_UPDATE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Subcategory.
        /// </summary>
        public static string TITLE_UPDATE_SUBCATEGOY {
            get {
                return ResourceManager.GetString("TITLE_UPDATE_SUBCATEGOY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update task.
        /// </summary>
        public static string TITLE_UPDATE_TASK {
            get {
                return ResourceManager.GetString("TITLE_UPDATE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the button below + to add one..
        /// </summary>
        public static string TITLE_USE_BUTTON_BELLOW_ADD_ONE {
            get {
                return ResourceManager.GetString("TITLE_USE_BUTTON_BELLOW_ADD_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the field above to Add new Subcategories.
        /// </summary>
        public static string TITLE_USE_FIELD_ABOVE_ADD_NEW_SUBCATEGORIES {
            get {
                return ResourceManager.GetString("TITLE_USE_FIELD_ABOVE_ADD_NEW_SUBCATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Terms.
        /// </summary>
        public static string TITLE_USE_TERMS {
            get {
                return ResourceManager.GetString("TITLE_USE_TERMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string TITLE_VERSION_NUMBER {
            get {
                return ResourceManager.GetString("TITLE_VERSION_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        public static string TITLE_VIEW_ALL {
            get {
                return ResourceManager.GetString("TITLE_VIEW_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking.
        /// </summary>
        public static string TITLE_WALKING {
            get {
                return ResourceManager.GetString("TITLE_WALKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is Pareto Principle?.
        /// </summary>
        public static string TITLE_WHAT_IS_PARETO_PRINCIPLE {
            get {
                return ResourceManager.GetString("TITLE_WHAT_IS_PARETO_PRINCIPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winning categories.
        /// </summary>
        public static string TITLE_WINNING_CATEGORIES {
            get {
                return ResourceManager.GetString("TITLE_WINNING_CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string TITLE_WORK {
            get {
                return ResourceManager.GetString("TITLE_WORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I&apos;m sure.
        /// </summary>
        public static string TITLE_YES_IAM_SURE {
            get {
                return ResourceManager.GetString("TITLE_YES_IAM_SURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are seeing the graphic {0}..
        /// </summary>
        public static string TITLE_YOU_ARE_SEEING_GRAPHIC_FOR {
            get {
                return ResourceManager.GetString("TITLE_YOU_ARE_SEEING_GRAPHIC_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can save more categories of the same type if you want :).
        /// </summary>
        public static string TITLE_YOU_CAN_SAVE_MORE_CATEGORIES {
            get {
                return ResourceManager.GetString("TITLE_YOU_CAN_SAVE_MORE_CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can save more subcategories of the same type if you want :).
        /// </summary>
        public static string TITLE_YOU_CAN_SAVE_MORE_SUBCATEGORIES {
            get {
                return ResourceManager.GetString("TITLE_YOU_CAN_SAVE_MORE_SUBCATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are seeing which categories make up the result for the: {0}..
        /// </summary>
        public static string TITLE_YOUR_ARE_SEEING_WHICH_CATEGORIES_MAKE_UP_THE_RESULT {
            get {
                return ResourceManager.GetString("TITLE_YOUR_ARE_SEEING_WHICH_CATEGORIES_MAKE_UP_THE_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are seeing which subcategories from {0} make up the result for the {1}..
        /// </summary>
        public static string TITLE_YOUR_ARE_SEEING_WHICH_SUBCATEGORIES_MAKE_UP_THE_RESULT {
            get {
                return ResourceManager.GetString("TITLE_YOUR_ARE_SEEING_WHICH_SUBCATEGORIES_MAKE_UP_THE_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your description.
        /// </summary>
        public static string TITLE_YOUR_DESCRIPTION {
            get {
                return ResourceManager.GetString("TITLE_YOUR_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your statistics.
        /// </summary>
        public static string TITLE_YOUR_STATISTICS {
            get {
                return ResourceManager.GetString("TITLE_YOUR_STATISTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube.
        /// </summary>
        public static string TITLE_YOUTUBE {
            get {
                return ResourceManager.GetString("TITLE_YOUTUBE", resourceCulture);
            }
        }
    }
}
