//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timerom.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timerom.App.ResourceText", typeof(ResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the Category “{0}”? You can’t undo this action..
        /// </summary>
        public static string DESCRIPTION_DELETE_CATEGORY {
            get {
                return ResourceManager.GetString("DESCRIPTION_DELETE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the task “{0}”? You can’t undo this action..
        /// </summary>
        public static string DESCRIPTION_DELETE_TASK {
            get {
                return ResourceManager.GetString("DESCRIPTION_DELETE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the goals of this App is to have a creative design. And for that, nothing better than using images to illustrate and amuse the user, right?
        ///
        ///All images used have a free license for use, and as a thank you, we leave below the links to the sites that our team used :).
        /// </summary>
        public static string DESCRIPTION_ILUSTRATIONS_INFORMATIONS {
            get {
                return ResourceManager.GetString("DESCRIPTION_ILUSTRATIONS_INFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No need to accelerate, just don&apos;t stop..
        /// </summary>
        public static string PHRASE_MENU_FLYOUT_1 {
            get {
                return ResourceManager.GetString("PHRASE_MENU_FLYOUT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this project.
        /// </summary>
        public static string TITLE_ABOUT_THIS_PROJECT {
            get {
                return ResourceManager.GetString("TITLE_ABOUT_THIS_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity progress.
        /// </summary>
        public static string TITLE_ACTIVITY_PROGRESS {
            get {
                return ResourceManager.GetString("TITLE_ACTIVITY_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Neutral Category.
        /// </summary>
        public static string TITLE_ADD_NEUTRAL_CATEGORY {
            get {
                return ResourceManager.GetString("TITLE_ADD_NEUTRAL_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Productive Category.
        /// </summary>
        public static string TITLE_ADD_PRODUCTIVE_CATEGORY {
            get {
                return ResourceManager.GetString("TITLE_ADD_PRODUCTIVE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string TITLE_ADD_TASK {
            get {
                return ResourceManager.GetString("TITLE_ADD_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Unproductive Category.
        /// </summary>
        public static string TITLE_ADD_UNPRODUCTIVE_CATEGORY {
            get {
                return ResourceManager.GetString("TITLE_ADD_UNPRODUCTIVE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It belongs to the category:.
        /// </summary>
        public static string TITLE_BELONGS_CATEGORY_TWO_POINTS {
            get {
                return ResourceManager.GetString("TITLE_BELONGS_CATEGORY_TWO_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string TITLE_BOOKS {
            get {
                return ResourceManager.GetString("TITLE_BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        public static string TITLE_BREAKFAST {
            get {
                return ResourceManager.GetString("TITLE_BREAKFAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string TITLE_CALL {
            get {
                return ResourceManager.GetString("TITLE_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TITLE_CANCEL {
            get {
                return ResourceManager.GetString("TITLE_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string TITLE_CATEGORIES {
            get {
                return ResourceManager.GetString("TITLE_CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name:.
        /// </summary>
        public static string TITLE_CATEGORY_NAME_TWO_POINTS {
            get {
                return ResourceManager.GetString("TITLE_CATEGORY_NAME_TWO_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an option.
        /// </summary>
        public static string TITLE_CHOOSE_AN_OPTION {
            get {
                return ResourceManager.GetString("TITLE_CHOOSE_AN_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string TITLE_CONTACT_US {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string TITLE_COURSES {
            get {
                return ResourceManager.GetString("TITLE_COURSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Category.
        /// </summary>
        public static string TITLE_CREATE_CATEGORY {
            get {
                return ResourceManager.GetString("TITLE_CREATE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Subcategory.
        /// </summary>
        public static string TITLE_CREATE_SUBCATEGORY {
            get {
                return ResourceManager.GetString("TITLE_CREATE_SUBCATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create task.
        /// </summary>
        public static string TITLE_CREATE_TASK {
            get {
                return ResourceManager.GetString("TITLE_CREATE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string TITLE_DASHBOARD {
            get {
                return ResourceManager.GetString("TITLE_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string TITLE_DAY {
            get {
                return ResourceManager.GetString("TITLE_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string TITLE_DAYS {
            get {
                return ResourceManager.GetString("TITLE_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        public static string TITLE_DELETE_CATEGORY {
            get {
                return ResourceManager.GetString("TITLE_DELETE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Task?.
        /// </summary>
        public static string TITLE_DELETE_TASK {
            get {
                return ResourceManager.GetString("TITLE_DELETE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string TITLE_DESCRIPTION_TWO_POINTS {
            get {
                return ResourceManager.GetString("TITLE_DESCRIPTION_TWO_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string TITLE_DETAILS {
            get {
                return ResourceManager.GetString("TITLE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        public static string TITLE_DINNER {
            get {
                return ResourceManager.GetString("TITLE_DINNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty list.
        /// </summary>
        public static string TITLE_EMPTY_LIST {
            get {
                return ResourceManager.GetString("TITLE_EMPTY_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends:.
        /// </summary>
        public static string TITLE_ENDS_TWO_POINTS {
            get {
                return ResourceManager.GetString("TITLE_ENDS_TWO_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string TITLE_FACEBOOK {
            get {
                return ResourceManager.GetString("TITLE_FACEBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string TITLE_FAMILY {
            get {
                return ResourceManager.GetString("TITLE_FAMILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string TITLE_FOOD {
            get {
                return ResourceManager.GetString("TITLE_FOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From {0} to {1}.
        /// </summary>
        public static string TITLE_FROM_TO {
            get {
                return ResourceManager.GetString("TITLE_FROM_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gym.
        /// </summary>
        public static string TITLE_GYM {
            get {
                return ResourceManager.GetString("TITLE_GYM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TITLE_HOME {
            get {
                return ResourceManager.GetString("TITLE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string TITLE_HOUR {
            get {
                return ResourceManager.GetString("TITLE_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string TITLE_HOURS {
            get {
                return ResourceManager.GetString("TITLE_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons and Illustrations used.
        /// </summary>
        public static string TITLE_ICONS_ILLUSTRATIONS_USED {
            get {
                return ResourceManager.GetString("TITLE_ICONS_ILLUSTRATIONS_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve your time.
        /// </summary>
        public static string TITLE_IMPROVE_YOUR_TIME {
            get {
                return ResourceManager.GetString("TITLE_IMPROVE_YOUR_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string TITLE_INSTAGRAM {
            get {
                return ResourceManager.GetString("TITLE_INSTAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        public static string TITLE_LUNCH {
            get {
                return ResourceManager.GetString("TITLE_LUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetings.
        /// </summary>
        public static string TITLE_MEETINGS {
            get {
                return ResourceManager.GetString("TITLE_MEETINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string TITLE_MINUTE {
            get {
                return ResourceManager.GetString("TITLE_MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string TITLE_MINUTES {
            get {
                return ResourceManager.GetString("TITLE_MINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string TITLE_NEUTRAL {
            get {
                return ResourceManager.GetString("TITLE_NEUTRAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No task for this date..
        /// </summary>
        public static string TITLE_NO_TASK_THIS_DATE {
            get {
                return ResourceManager.GetString("TITLE_NO_TASK_THIS_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal projects.
        /// </summary>
        public static string TITLE_PERSONAL_PROJECTS {
            get {
                return ResourceManager.GetString("TITLE_PERSONAL_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner.
        /// </summary>
        public static string TITLE_PLANNER {
            get {
                return ResourceManager.GetString("TITLE_PLANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcasts.
        /// </summary>
        public static string TITLE_PODCASTS {
            get {
                return ResourceManager.GetString("TITLE_PODCASTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string TITLE_PRIVACY_POLICY {
            get {
                return ResourceManager.GetString("TITLE_PRIVACY_POLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product search.
        /// </summary>
        public static string TITLE_PRODUCT_SEARCH {
            get {
                return ResourceManager.GetString("TITLE_PRODUCT_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productive.
        /// </summary>
        public static string TITLE_PRODUCTIVE {
            get {
                return ResourceManager.GetString("TITLE_PRODUCTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        public static string TITLE_PURCHASES {
            get {
                return ResourceManager.GetString("TITLE_PURCHASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string TITLE_REPORTS {
            get {
                return ResourceManager.GetString("TITLE_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TITLE_SAVE {
            get {
                return ResourceManager.GetString("TITLE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salving ....
        /// </summary>
        public static string TITLE_SAVING {
            get {
                return ResourceManager.GetString("TITLE_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name.
        /// </summary>
        public static string TITLE_SEARCH_BY_NAME {
            get {
                return ResourceManager.GetString("TITLE_SEARCH_BY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Category.
        /// </summary>
        public static string TITLE_SELECT_CATEGORY {
            get {
                return ResourceManager.GetString("TITLE_SELECT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category for your Task.
        /// </summary>
        public static string TITLE_SELECT_CATEGORY_FOR_YOUR_TASK {
            get {
                return ResourceManager.GetString("TITLE_SELECT_CATEGORY_FOR_YOUR_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Subcategory for your Task..
        /// </summary>
        public static string TITLE_SELECT_SUBCATEGORY_YOUR_TASK {
            get {
                return ResourceManager.GetString("TITLE_SELECT_SUBCATEGORY_YOUR_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social media.
        /// </summary>
        public static string TITLE_SOCIAL_MEDIA {
            get {
                return ResourceManager.GetString("TITLE_SOCIAL_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string TITLE_SPORT {
            get {
                return ResourceManager.GetString("TITLE_SPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Task.
        /// </summary>
        public static string TITLE_START_TASK {
            get {
                return ResourceManager.GetString("TITLE_START_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts:.
        /// </summary>
        public static string TITLE_STARTS_TWO_POINTS {
            get {
                return ResourceManager.GetString("TITLE_STARTS_TWO_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studies.
        /// </summary>
        public static string TITLE_STUDIES {
            get {
                return ResourceManager.GetString("TITLE_STUDIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studing English.
        /// </summary>
        public static string TITLE_STUDING_ENGLISH {
            get {
                return ResourceManager.GetString("TITLE_STUDING_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub categories:.
        /// </summary>
        public static string TITLE_SUBCATEGORIES_TITLE_TWO_POINTS {
            get {
                return ResourceManager.GetString("TITLE_SUBCATEGORIES_TITLE_TWO_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory:.
        /// </summary>
        public static string TITLE_SUBCATEGORY_TITLE_TWO_POINTS {
            get {
                return ResourceManager.GetString("TITLE_SUBCATEGORY_TITLE_TWO_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string TITLE_SUCCESS {
            get {
                return ResourceManager.GetString("TITLE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supermarket.
        /// </summary>
        public static string TITLE_SUPERMARKET {
            get {
                return ResourceManager.GetString("TITLE_SUPERMARKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task details.
        /// </summary>
        public static string TITLE_TASK_DETAILS {
            get {
                return ResourceManager.GetString("TITLE_TASK_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task title:.
        /// </summary>
        public static string TITLE_TASK_TITLE_TWO_POINTS {
            get {
                return ResourceManager.GetString("TITLE_TASK_TITLE_TWO_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TITLE_TASKS {
            get {
                return ResourceManager.GetString("TITLE_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        public static string TITLE_TECHNOLOGY {
            get {
                return ResourceManager.GetString("TITLE_TECHNOLOGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is {0}% of your day..
        /// </summary>
        public static string TITLE_THIS_IS_PERCENTAGE_YOUR_DAY {
            get {
                return ResourceManager.GetString("TITLE_THIS_IS_PERCENTAGE_YOUR_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total of {0} tasks.
        /// </summary>
        public static string TITLE_TOTAL_OF_TASKS {
            get {
                return ResourceManager.GetString("TITLE_TOTAL_OF_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        public static string TITLE_TOUR {
            get {
                return ResourceManager.GetString("TITLE_TOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string TITLE_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("TITLE_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unproductive.
        /// </summary>
        public static string TITLE_UNPRODUCTIVE {
            get {
                return ResourceManager.GetString("TITLE_UNPRODUCTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Category.
        /// </summary>
        public static string TITLE_UPDATE_CATEGORY {
            get {
                return ResourceManager.GetString("TITLE_UPDATE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Subcategory.
        /// </summary>
        public static string TITLE_UPDATE_SUBCATEGOY {
            get {
                return ResourceManager.GetString("TITLE_UPDATE_SUBCATEGOY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update task.
        /// </summary>
        public static string TITLE_UPDATE_TASK {
            get {
                return ResourceManager.GetString("TITLE_UPDATE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the button below + to add one..
        /// </summary>
        public static string TITLE_USE_BUTTON_BELLOW_ADD_ONE {
            get {
                return ResourceManager.GetString("TITLE_USE_BUTTON_BELLOW_ADD_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the field above to Add new Subcategories.
        /// </summary>
        public static string TITLE_USE_FIELD_ABOVE_ADD_NEW_SUBCATEGORIES {
            get {
                return ResourceManager.GetString("TITLE_USE_FIELD_ABOVE_ADD_NEW_SUBCATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Terms.
        /// </summary>
        public static string TITLE_USE_TERMS {
            get {
                return ResourceManager.GetString("TITLE_USE_TERMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string TITLE_VERSION_NUMBER {
            get {
                return ResourceManager.GetString("TITLE_VERSION_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        public static string TITLE_VIEW_ALL {
            get {
                return ResourceManager.GetString("TITLE_VIEW_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking.
        /// </summary>
        public static string TITLE_WALKING {
            get {
                return ResourceManager.GetString("TITLE_WALKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string TITLE_WORK {
            get {
                return ResourceManager.GetString("TITLE_WORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I&apos;m sure.
        /// </summary>
        public static string TITLE_YES_IAM_SURE {
            get {
                return ResourceManager.GetString("TITLE_YES_IAM_SURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can save more categories of the same type if you want :).
        /// </summary>
        public static string TITLE_YOU_CAN_SAVE_MORE_CATEGORIES {
            get {
                return ResourceManager.GetString("TITLE_YOU_CAN_SAVE_MORE_CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can save more subcategories of the same type if you want :).
        /// </summary>
        public static string TITLE_YOU_CAN_SAVE_MORE_SUBCATEGORIES {
            get {
                return ResourceManager.GetString("TITLE_YOU_CAN_SAVE_MORE_SUBCATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your description.
        /// </summary>
        public static string TITLE_YOUR_DESCRIPTION {
            get {
                return ResourceManager.GetString("TITLE_YOUR_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube.
        /// </summary>
        public static string TITLE_YOUTUBE {
            get {
                return ResourceManager.GetString("TITLE_YOUTUBE", resourceCulture);
            }
        }
    }
}
